export type ExerciseLibraryItem = {
  name: string
  group: string
  gifUrl?: string
}

export const EXERCISE_LIBRARY: ExerciseLibraryItem[] = [
  { group: 'Peito', name: 'Supino reto com barra' },
  { group: 'Peito', name: 'Supino reto com halteres' },
  { group: 'Peito', name: 'Supino inclinado com barra' },
  { group: 'Peito', name: 'Supino inclinado com halteres' },
  { group: 'Peito', name: 'Supino declinado com barra' },
  { group: 'Peito', name: 'Supino máquina' },
  { group: 'Peito', name: 'Crucifixo reto com halteres' },
  { group: 'Peito', name: 'Crucifixo inclinado com halteres' },
  { group: 'Peito', name: 'Crucifixo na máquina' },
  { group: 'Peito', name: 'Crossover polia alta' },
  { group: 'Peito', name: 'Crossover polia média' },
  { group: 'Peito', name: 'Crossover polia baixa' },
  { group: 'Peito', name: 'Flexão de braço' },
  { group: 'Peito', name: 'Flexão inclinada' },
  { group: 'Peito', name: 'Flexão declinada' },
  { group: 'Peito', name: 'Paralelas com foco em peito' },

  { group: 'Costas', name: 'Puxada frontal aberta' },
  { group: 'Costas', name: 'Puxada frontal neutra' },
  { group: 'Costas', name: 'Puxada frontal supinada' },
  { group: 'Costas', name: 'Barra fixa pronada' },
  { group: 'Costas', name: 'Barra fixa supinada' },
  { group: 'Costas', name: 'Remada curvada com barra' },
  { group: 'Costas', name: 'Remada curvada supinada' },
  { group: 'Costas', name: 'Remada unilateral com halter' },
  { group: 'Costas', name: 'Remada baixa triângulo' },
  { group: 'Costas', name: 'Remada baixa aberta' },
  { group: 'Costas', name: 'Remada cavalinho' },
  { group: 'Costas', name: 'Remada máquina' },
  { group: 'Costas', name: 'Pulldown com braços estendidos' },
  { group: 'Costas', name: 'Pullover na polia' },
  { group: 'Costas', name: 'Levantamento terra' },
  { group: 'Costas', name: 'Hiperextensão lombar' },

  { group: 'Ombros', name: 'Desenvolvimento militar com barra' },
  { group: 'Ombros', name: 'Desenvolvimento com halteres' },
  { group: 'Ombros', name: 'Desenvolvimento máquina' },
  { group: 'Ombros', name: 'Elevação lateral com halteres' },
  { group: 'Ombros', name: 'Elevação lateral na polia' },
  { group: 'Ombros', name: 'Elevação frontal com halteres' },
  { group: 'Ombros', name: 'Elevação frontal com barra' },
  { group: 'Ombros', name: 'Crucifixo inverso com halteres' },
  { group: 'Ombros', name: 'Crucifixo inverso na máquina' },
  { group: 'Ombros', name: 'Face pull' },
  { group: 'Ombros', name: 'Remada alta' },
  { group: 'Ombros', name: 'Encolhimento com halteres' },
  { group: 'Ombros', name: 'Encolhimento com barra' },

  { group: 'Bíceps', name: 'Rosca direta com barra' },
  { group: 'Bíceps', name: 'Rosca direta barra W' },
  { group: 'Bíceps', name: 'Rosca alternada com halteres' },
  { group: 'Bíceps', name: 'Rosca martelo' },
  { group: 'Bíceps', name: 'Rosca concentrada' },
  { group: 'Bíceps', name: 'Rosca Scott barra W' },
  { group: 'Bíceps', name: 'Rosca Scott máquina' },
  { group: 'Bíceps', name: 'Rosca na polia baixa' },
  { group: 'Bíceps', name: 'Rosca inclinada com halteres' },
  { group: 'Bíceps', name: 'Rosca 21' },

  { group: 'Tríceps', name: 'Tríceps corda na polia' },
  { group: 'Tríceps', name: 'Tríceps barra reta na polia' },
  { group: 'Tríceps', name: 'Tríceps barra V na polia' },
  { group: 'Tríceps', name: 'Tríceps francês com halter' },
  { group: 'Tríceps', name: 'Tríceps francês com barra W' },
  { group: 'Tríceps', name: 'Tríceps testa com barra W' },
  { group: 'Tríceps', name: 'Tríceps coice com halter' },
  { group: 'Tríceps', name: 'Tríceps banco' },
  { group: 'Tríceps', name: 'Paralelas com foco em tríceps' },
  { group: 'Tríceps', name: 'Supino fechado' },

  { group: 'Quadríceps', name: 'Agachamento livre' },
  { group: 'Quadríceps', name: 'Agachamento frontal' },
  { group: 'Quadríceps', name: 'Agachamento sumô' },
  { group: 'Quadríceps', name: 'Leg press 45' },
  { group: 'Quadríceps', name: 'Leg press horizontal' },
  { group: 'Quadríceps', name: 'Cadeira extensora' },
  { group: 'Quadríceps', name: 'Afundo com halteres' },
  { group: 'Quadríceps', name: 'Passada caminhando' },
  { group: 'Quadríceps', name: 'Búlgaro com halteres' },
  { group: 'Quadríceps', name: 'Hack squat' },
  { group: 'Quadríceps', name: 'Agachamento no Smith' },
  { group: 'Quadríceps', name: 'Step-up no banco' },

  { group: 'Posterior e glúteos', name: 'Mesa flexora' },
  { group: 'Posterior e glúteos', name: 'Cadeira flexora' },
  { group: 'Posterior e glúteos', name: 'Flexora em pé' },
  { group: 'Posterior e glúteos', name: 'Stiff com barra' },
  { group: 'Posterior e glúteos', name: 'Stiff com halteres' },
  { group: 'Posterior e glúteos', name: 'Levantamento terra romeno' },
  { group: 'Posterior e glúteos', name: 'Elevação pélvica com barra' },
  { group: 'Posterior e glúteos', name: 'Hip thrust máquina' },
  { group: 'Posterior e glúteos', name: 'Glúteo na polia' },
  { group: 'Posterior e glúteos', name: 'Abdução de quadril máquina' },
  { group: 'Posterior e glúteos', name: 'Abdução com miniband' },
  { group: 'Posterior e glúteos', name: 'Coice no cabo' },
  { group: 'Posterior e glúteos', name: 'Bom dia com barra' },

  { group: 'Panturrilhas', name: 'Panturrilha em pé' },
  { group: 'Panturrilhas', name: 'Panturrilha sentado' },
  { group: 'Panturrilhas', name: 'Panturrilha no leg press' },
  { group: 'Panturrilhas', name: 'Panturrilha unilateral' },
  { group: 'Panturrilhas', name: 'Panturrilha no Smith' },

  { group: 'Abdômen', name: 'Abdominal supra' },
  { group: 'Abdômen', name: 'Abdominal infra' },
  { group: 'Abdômen', name: 'Abdominal oblíquo' },
  { group: 'Abdômen', name: 'Abdominal bicicleta' },
  { group: 'Abdômen', name: 'Prancha frontal' },
  { group: 'Abdômen', name: 'Prancha lateral' },
  { group: 'Abdômen', name: 'Abdominal na polia' },
  { group: 'Abdômen', name: 'Elevação de pernas' },
  { group: 'Abdômen', name: 'Elevação de pernas na barra' },
  { group: 'Abdômen', name: 'Russian twist' },
  { group: 'Abdômen', name: 'Dead bug' },
  { group: 'Abdômen', name: 'Mountain climber' },

  { group: 'Cardio e funcional', name: 'Esteira caminhada' },
  { group: 'Cardio e funcional', name: 'Esteira corrida' },
  { group: 'Cardio e funcional', name: 'Bicicleta ergométrica' },
  { group: 'Cardio e funcional', name: 'Elíptico' },
  { group: 'Cardio e funcional', name: 'Remo ergômetro' },
  { group: 'Cardio e funcional', name: 'Escada ergométrica' },
  { group: 'Cardio e funcional', name: 'Burpee' },
  { group: 'Cardio e funcional', name: 'Polichinelo' },
  { group: 'Cardio e funcional', name: 'Kettlebell swing' },
  { group: 'Cardio e funcional', name: 'Corda naval' },
  { group: 'Cardio e funcional', name: 'Sled push' },
  { group: 'Cardio e funcional', name: 'Farmer walk' },
]

export const EXERCISE_GROUPS = Array.from(new Set(EXERCISE_LIBRARY.map(exercise => exercise.group)))
